apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-logger
  template:
    metadata:
      labels:
        app: statistics-logger
    spec:
      containers:
      - name: statistics-logger
        image: statistics-logger:latest 
        imagePullPolicy: IfNotPresent
